# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5659eb40af5e9670a92743f7c578e2fe"
name = "Fairdrops"
application_url = "https://fairdrops.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = [ "orders/paid" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_locations,read_orders,read_products,write_draft_orders,write_products"

[auth]
redirect_urls = [ "https://fairdrops.onrender.com/auth/callback" ]

[app_proxy]
url = "https://plans-enjoy-half-yeast.trycloudflare.com/apps/raffle"
subpath = "raffle"
prefix = "apps"
